# Generated by Django 3.0.5 on 2020-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
