# Generated by Django 3.0.5 on 2020-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connector', models.IntegerField()),
                ('reply', models.TextField(blank=True)),
            ],
        ),
    ]
