# Generated by Django 3.0.5 on 2020-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200422_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=models.TextField(),
        ),
    ]
