# Generated by Django 3.0.5 on 2020-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phonenumber',
            field=models.CharField(default=8688951346, max_length=100),
            preserve_default=False,
        ),
    ]
